
        <h1><?php echo $heading ?> <?php echo $year ?></h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Tel</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Sampath</td>
                    <td>Colombo</td>
                    <td>sampath@gmail.com</td>
                    <td>0112456789</td>
                </tr>
                <tr>
                    <td>Kamal</td>
                    <td>Kandy</td>
                    <td>kamal@gmail.com</td>
                    <td>0112456789</td>
                </tr>
                <tr>
                    <td>Amal</td>
                    <td>Colombo</td>
                    <td>amal@gmail.com</td>
                    <td>0112456789</td>
                </tr>
                <tr>
                    <td>Gayani</td>
                    <td>Matara</td>
                    <td>gayani@gmail.com</td>
                    <td>0432456789</td>
                </tr>
            </tbody>
        </table>
    